/**
 * awsibnj v3 — TypeScript Type Generator
 *
 * Generate TypeScript interface declarations from:
 *  - Inferred schemas (SchemaInference output)
 *  - User-defined schemas
 *  - Raw API data samples
 *
 * Output:
 *  - TypeScript interfaces
 *  - Type guards
 *  - Optional JSDoc comments
 */

class TypeGenerator {
  /**
   * @param {object} options
   * @param {boolean} options.exportTypes     Add 'export' to generated types (default true)
   * @param {boolean} options.readonlyFields  Mark fields as readonly (default false)
   * @param {boolean} options.includeJSDoc    Add JSDoc comments (default true)
   * @param {string}  options.indent          Indentation string (default '  ')
   */
  constructor(options = {}) {
    this.exportTypes = options.exportTypes !== false;
    this.readonlyFields = options.readonlyFields || false;
    this.includeJSDoc = options.includeJSDoc !== false;
    this.indent = options.indent || '  ';
  }

  /**
   * Generate TypeScript interface from a schema.
   * @param {string} name   Interface name
   * @param {object} schema Schema object { field: { type, required, nullable } }
   * @returns {string} TypeScript interface code
   */
  fromSchema(name, schema) {
    if (!schema || typeof schema !== 'object') return '';

    const lines = [];
    const exportPrefix = this.exportTypes ? 'export ' : '';

    if (this.includeJSDoc) {
      lines.push('/**');
      lines.push(` * Auto-generated by awsibnj v3`);
      lines.push(` * @generated`);
      lines.push(' */');
    }

    lines.push(`${exportPrefix}interface ${name} {`);

    for (const [field, spec] of Object.entries(schema)) {
      const tsType = this._schemaTypeToTS(spec);
      const optional = spec.required === false ? '?' : '';
      const readonly = this.readonlyFields ? 'readonly ' : '';
      const nullable = spec.nullable ? ' | null' : '';

      if (this.includeJSDoc && spec.pattern) {
        lines.push(`${this.indent}/** Pattern: ${spec.pattern} */`);
      }

      lines.push(`${this.indent}${readonly}${field}${optional}: ${tsType}${nullable};`);
    }

    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Generate TypeScript interface from raw data.
   * @param {string} name  Interface name
   * @param {object} data  Sample data object
   * @returns {string} TypeScript interface code
   */
  fromData(name, data) {
    if (!data || typeof data !== 'object') return '';

    const lines = [];
    const exportPrefix = this.exportTypes ? 'export ' : '';

    if (this.includeJSDoc) {
      lines.push('/**');
      lines.push(` * Auto-generated by awsibnj v3`);
      lines.push(` * @generated`);
      lines.push(' */');
    }

    lines.push(`${exportPrefix}interface ${name} {`);

    for (const [key, value] of Object.entries(data)) {
      const tsType = this._inferTSType(value);
      const readonly = this.readonlyFields ? 'readonly ' : '';
      lines.push(`${this.indent}${readonly}${key}: ${tsType};`);
    }

    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Generate a type guard function.
   * @param {string} name   Interface name
   * @param {object} schema Schema with required fields
   * @returns {string} TypeScript type guard code
   */
  generateTypeGuard(name, schema) {
    const lines = [];
    const exportPrefix = this.exportTypes ? 'export ' : '';

    lines.push(`${exportPrefix}function is${name}(value: unknown): value is ${name} {`);
    lines.push(`${this.indent}if (typeof value !== 'object' || value === null) return false;`);
    lines.push(`${this.indent}const obj = value as Record<string, unknown>;`);

    for (const [field, spec] of Object.entries(schema)) {
      if (spec.required !== false) {
        const tsType = this._schemaTypeToTS(spec);
        const checks = this._generateTypeCheck(field, tsType, spec);
        lines.push(`${this.indent}${checks}`);
      }
    }

    lines.push(`${this.indent}return true;`);
    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Generate multiple interfaces from a nested data structure.
   * @param {string} baseName Base name for the root interface
   * @param {object} data     Sample data
   * @returns {string} All generated TypeScript code
   */
  fromNestedData(baseName, data) {
    const interfaces = [];
    this._generateNested(baseName, data, interfaces);
    return interfaces.join('\n\n');
  }

  _generateNested(name, data, interfaces) {
    if (!data || typeof data !== 'object' || Array.isArray(data)) return;

    const lines = [];
    const exportPrefix = this.exportTypes ? 'export ' : '';

    if (this.includeJSDoc) {
      lines.push('/**');
      lines.push(` * Auto-generated by awsibnj v3`);
      lines.push(` * @generated`);
      lines.push(' */');
    }

    lines.push(`${exportPrefix}interface ${name} {`);

    for (const [key, value] of Object.entries(data)) {
      const readonly = this.readonlyFields ? 'readonly ' : '';

      if (value !== null && typeof value === 'object' && !Array.isArray(value) && !(value instanceof Date)) {
        const nestedName = name + this._capitalize(key);
        lines.push(`${this.indent}${readonly}${key}: ${nestedName};`);
        this._generateNested(nestedName, value, interfaces);
      } else if (Array.isArray(value) && value.length > 0 && typeof value[0] === 'object' && value[0] !== null) {
        const nestedName = name + this._capitalize(key) + 'Item';
        lines.push(`${this.indent}${readonly}${key}: ${nestedName}[];`);
        this._generateNested(nestedName, value[0], interfaces);
      } else {
        const tsType = this._inferTSType(value);
        lines.push(`${this.indent}${readonly}${key}: ${tsType};`);
      }
    }

    lines.push('}');
    interfaces.push(lines.join('\n'));
  }

  _schemaTypeToTS(spec) {
    const type = spec.type || 'any';
    switch (type) {
      case 'string':  return 'string';
      case 'number':
      case 'integer':
      case 'float':   return 'number';
      case 'boolean': return 'boolean';
      case 'date':    return 'Date | string';
      case 'array':   return 'unknown[]';
      case 'object':
      case 'json':    return 'Record<string, unknown>';
      case 'any':     return 'unknown';
      default:        return 'unknown';
    }
  }

  _inferTSType(value) {
    if (value === null) return 'null';
    if (value === undefined) return 'undefined';
    if (typeof value === 'string') return 'string';
    if (typeof value === 'number') return 'number';
    if (typeof value === 'boolean') return 'boolean';
    if (value instanceof Date) return 'Date';
    if (Array.isArray(value)) {
      if (value.length === 0) return 'unknown[]';
      const itemType = this._inferTSType(value[0]);
      return `${itemType}[]`;
    }
    if (typeof value === 'object') return 'Record<string, unknown>';
    return 'unknown';
  }

  _generateTypeCheck(field, tsType, spec) {
    const nullable = spec.nullable ? ` && obj['${field}'] !== null` : '';
    switch (tsType) {
      case 'string':
        return `if (typeof obj['${field}'] !== 'string'${nullable}) return false;`;
      case 'number':
        return `if (typeof obj['${field}'] !== 'number'${nullable}) return false;`;
      case 'boolean':
        return `if (typeof obj['${field}'] !== 'boolean'${nullable}) return false;`;
      default:
        return `if (obj['${field}'] === undefined) return false;`;
    }
  }

  _capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}

module.exports = { TypeGenerator };
